language: node_js
node_js:
  - lts/*
cache:
  npm: false
  directories:
    - "~/.pnpm-store"

install:
  - pnpm install

script:
  - pnpm build
script:
  - pnpm test
script:
  - pnpm changeset version

# before_deploy:
#   - echo "@mjefi:registry=https://npm.pkg.github.com/" > "$HOME/.npmrc"
#   - echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > "$HOME/.npmrc"

# deploy:
#   provider: script
#   script: npm run publish
#   skip_cleanup: true
#   on:
#     branch: master

# after_success:
#   - git config --global user.email "travis@travis-ci.org"
#   - git config --global user.name "Travis CI"
#   - git push https://$GITHUB_TOKEN@github.com/mjefi/changesets-workflow-with-ci.git HEAD:master
#   - git push https://$GITHUB_TOKEN@github.com/mjefi/changesets-workflow-with-ci.git HEAD:master --tags
