name: Auto merge

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # Auto merge when the branch name is the changset release branch:
      - name: "Merge pull request"
        if: github.ref_name == 'changeset-release/main'
        uses: "actions/github-script@v6"
        with:
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            await github.rest.pulls.merge({
              merge_method: "squash",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })
