name: Automerge
on:
  pull_request:
    branches:
      - main
jobs:
  Enable-Automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        if: github.ref_name == 'changeset-release/main'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.PAT_GITHUB_ACTIONS}}
