name: Automerge
on:
  pull_request:
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
       - name: "Merge pull request"
        if: github.ref_name == 'changeset-release/main'
        uses: "actions/github-script@v6"
        env:
          GITHUB_TOKEN: ${{secrets.PAT_GITHUB_ACTIONS}}
        with:
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            await github.rest.pulls.merge({
              merge_method: "squash",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })